name: grid
default_ecosystem: ethereum

ethereum:
  default_network: local
  local:
    default_provider: foundry

base:
  default_network: mainnet
  mainnet:
    default_provider: geth

foundry:
  fork:
    ethereum:
      goerli:
        upstream_provider: infura
      mainnet:
        upstream_provider: infura

vyper:
  evm_version: paris

solidity:
  evm_version: paris

plugins:
  - solidity
  - vyper
  - base
  - foundry
